### ISSUE TITLE
The dataset is not available

### ISSUE THREAD

**Issue by weimengting** [SimonGiebenhain/NPHM#25]
Hi, I didn't get any response after I filled the form to request the NPHM dataset.

**Comment by SimonGiebenhain** [comment]
Hi @weimengting,

are you referring to the NPHM dataset (v1 and v2) or about the test data from the MonoNPHM paper?
For the latter I recently sent an email.
Please let me know what you are missing, such that I can help.

**Comment by weimengting** [comment]
Hi,

Thanks for the instant reply. I want to get the v1 version published in this paper: Learning Neural Parametric Head Models (NPHM). I got the link before but then I didn't have enough space to store it. Now I want to download the data using the link sent me, but it shows invaild. 

![Screenshot from 2024-10-01 15-59-22](https://github.com/user-attachments/assets/88091520-8e7a-4fa1-9bc7-9115fe261f4d)


> Hi @weimengting,
> 
> are you referring to the NPHM dataset (v1 and v2) or about the test data from the MonoNPHM paper? For the latter I recently sent an email. Please let me know what you are missing, such that I can help.
