### ISSUE TITLE
Training on Facescape Dataset

### ISSUE THREAD

**Issue by aejion** [SimonGiebenhain/NPHM#7]
Hi, it's a fantastic work!

I have a question about training NPHM on Facescape Dataset. First, I have prepare the neutral expression data to train the Identity Network, and it can obtain a nice result as the following image shown.
<img width="482" alt="image" src="https://github.com/SimonGiebenhain/NPHM/assets/72380054/41b7ec36-89ef-4fc4-95ba-0db8c6376afb">

[facescape_neutral.zip](https://github.com/SimonGiebenhain/NPHM/files/12066368/facescape_neutral.zip)

And then I use the registered mesh of Facescape dataset and run the scripts/data_processing/sample_deformation_field.py to prepare samples, then train the forward deformation fields. But the results on the training set seems to be wrong. Could you please help me figure out the problem?

<img width="300" alt="image" src="https://github.com/SimonGiebenhain/NPHM/assets/72380054/d6d6c273-bd7b-43da-aa53-4fd7af11d2e5">
<img width="300" alt="image" src="https://github.com/SimonGiebenhain/NPHM/assets/72380054/1e48319a-a69a-417f-b4f7-161b5849bdb0">

[facescape_expression.zip](https://github.com/SimonGiebenhain/NPHM/files/12066421/facescape_expression.zip)

Thanks!

**Comment by SimonGiebenhain** [comment]
Hi, 

I assume that by "seem wrong" you mean that there are tiny ripples/imperfections in the expression reconstruction? Or is it the fact that the expression is not captured accurately?

Regarding the first problem, I guess you generated the result while the `.training` attribute of the deformation network set to `True`.  [Here](https://github.com/SimonGiebenhain/NPHM/blob/0bb36c92780ce7b899c55c04d827cda64a5cedd5/src/NPHM/models/deepSDF.py#L221C17-L221C17) you can see that during training I add a bit of noise to the "compressed" identity code. Please note that I don't know if that is a good or bad thing, but there was little time and I tried to avoid overfitting.

Regarding the second problem: Maybe the network just needs to train longer. In general learning forward deformations in the style of NPHM requires detailed and consistent (!) registrations. I believe that learning backward deformations, like i3DMM and especially ImFace, is promising and does not require registrations at all.
