### ISSUE TITLE
Fitting and model latent code question

### ISSUE THREAD

**Issue by wengjincheng** [SimonGiebenhain/NPHM#9]
Hi,

Thanks for your great work, I have one question that whether I just need to fit Head points cloud to get global id latent code and expression latent code? But the local id latent code is not needed?

**Comment by SimonGiebenhain** [comment]
Hi, 

the id latent code is composed of a global part and a multiple local latents. When attempting to reconstruct a head based on a point cloud, you have to fit the identity code (including both local and global part), as well as, the expression code (for expressions everything is modeled in a single global code and there are no local codes)

**Comment by wengjincheng** [comment]
> Hi,
> 
> the id latent code is composed of a global part and a multiple local latents. When attempting to reconstruct a head based on a point cloud, you have to fit the identity code (including both local and global part), as well as, the expression code (for expressions everything is modeled in a single global code and there are no local codes)

Thanks for your clear reply
